# Generated by Django 4.2.23 on 2025-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
